ALTER TABLE `aswsii`.`envio_facturas_recibidas`   
	ADD COLUMN `REG_FR_DF_ISP_DI_DT1_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT1_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_ISP_DI_DT2_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT2_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_ISP_DI_DT3_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT3_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_ISP_DI_DT4_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT4_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_ISP_DI_DT5_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT5_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_ISP_DI_DT6_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_ISP_DI_DT6_CuotaREquivalencia`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT1_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT1_ImporteCompensacionREAGYP`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT2_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT2_ImporteCompensacionREAGYP`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT3_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT3_ImporteCompensacionREAGYP`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT4_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT4_ImporteCompensacionREAGYP`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT5_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT5_ImporteCompensacionREAGYP`,
	ADD COLUMN `REG_FR_DF_DGI_DI_DT6_BienInversion` VARCHAR(1) DEFAULT 'N' NULL AFTER `REG_FR_DF_DGI_DI_DT6_ImporteCompensacionREAGYP`;
