/*
SQLyog Community v12.4.2 (64 bit)
MySQL - 5.7.17-log : Database - aswsii
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`aswsii` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `aswsii`;

/*Table structure for table `envio_facturas_recibidas` */

DROP TABLE IF EXISTS `envio_facturas_recibidas`;

CREATE TABLE `envio_facturas_recibidas` (
  `IDEnvioFacturasRecibidas` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Es un identificador único autoincremental para cualquier registro de la tabla.',
  `Origen` VARCHAR(255) NOT NULL COMMENT 'Indica el origen del registro. Es un campo libre y su intención es reflejar el sistema que creó esta información.\nPor ejemplo si proviene de la carga de un fichero Excel o CSV, aquí se indicará el nombre de fichero con extensión',
  `FechaHoraCreacion` DATETIME NOT NULL COMMENT 'Fecha y hora en la que el sistema de alimentación creó el registro.',
  `EnvioInmediato` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Indica si se desea que el servicio de envío presente la factura inmediatamaente. Posibles valores:\n1 = Tan pronto como el sistema detecte el registro lo comunicará a la AEAT\n0 = Espera a la intervención manual del operador por el interfaz Web para proceder al envío',
  `Enviada` TINYINT(1) NOT NULL DEFAULT '0' COMMENT 'Indica si la factura ha sido enviada a la AEAT, independientemente de si ese envío ha provocado errores o no. Posibles valores:\n0 = Factura no enviada\n1 = Factura enviada\n\n',
  `Resultado` VARCHAR(255) DEFAULT NULL COMMENT 'Resultado del envío. Posibles valores:\nERROR: Se ha producido un error, bien porque la plataforma ha fallado o porque alguno de los campos es incorrecto, ver el campo "Mensaje para comprobar la razón"\nINCORRECTO: El envio ha sido incorrecto, ver el campo "Mensaje para comprobar la razón"\nCORRECTO: El envio ha sido correctamente registrado\n',
  `CSV` VARCHAR(255) DEFAULT NULL COMMENT 'Código seguro de verificación. Equivale al número de registro en los envios CORRECTO',
  `Mensaje` TEXT COMMENT 'Mensaje resultado del envío, de transcendencia en envío con ERROR o INCORRECTO',
  `XML_Enviado` TEXT COMMENT 'XML SOAP del último envío realizado',
  `CAB_IDVersionSii` VARCHAR(3) NOT NULL DEFAULT '0.7' COMMENT 'Cabecera - IDVersionSii\nIdentificación de la versión del esquema utilizado para el intercambio de información. La versión actual es ''0.7'' por eso tiene ese valor por defecto.\n',
  `CAB_Titular_NombreRazon` VARCHAR(40) NOT NULL COMMENT 'Cabecera - Titular - NombreRazon\nNombre-razón social del Titular del libro de registro de facturas recibidas',
  `CAB_Titular_NIFRepresentante` VARCHAR(9) DEFAULT NULL COMMENT 'Cabecera - Titular - NIFRepresentante\nNIF del representante del titular del libro de registro',
  `CAB_Titular_NIF` VARCHAR(9) NOT NULL COMMENT 'Cabecera - Titular - NIF\nNIF asociado al titular del libro de registro',
  `CAB_TipoComunicacion` VARCHAR(2) NOT NULL COMMENT 'Cabecera - Titular - TipoComunicacion\nTipo de operación (alta, modificación). Posibles valores:\nA0 = Alta de facturas/registro\nA1 = Modificación de facturas/registros (errores registrales)\nA4 = Modificación Factura Régimen de Viajeros',
  `REG_PI_Ejercicio` INT(4) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - PeriodoImpositivo - Ejercicio\nEjercicio impositivo de la factura, normalmente el año.',
  `REG_PI_Periodo` VARCHAR(2) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - PeriodoImpositivo - Periodo\nPeriodo impositivo de la factura. Posibles valores:\n01 = Enero\n02  = Febrero\n03  = Marzo\n04  = Abril\n05  = Mayo\n06  = Junio\n07  = Julio\n08  = Agosto\n09  = Septiembre\n10 =  Octubre\n11 =  Noviembre\n12  = Diciembre\n0A  = Anual',
  `REG_IDF_IDEF_NIF` VARCHAR(9) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - IDEmisorFactura - NIF\nNIF asociado al emisor de la factura.',
  `REG_IDF_IDEF_IDOtro_CodigoPais` VARCHAR(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - IDEmisorFactura - IDOtro - CodigoPais\nIDOtro, solo es de obligado cumplimiento si hay que proporcionar información adicional de la contraparte. Si aun no siendo obligado se cumplimenta esta información aparece en la consulta directa de la web de AEAT.\nCódigo del país asociado contraparte de la operación (cliente) de facturas expedidas (ISO 3166-1 alpha-2 codes)',
  `REG_IDF_IDEF_IDOtro_IDType` VARCHAR(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - IDEmisorFactura - IDOtro - IDType\nClave para establecer el tipo de identificación en el pais de residencia. Posibles valores:\n02 = NIF-IVA\n03 = PASAPORTE\n04 = DOCUMENTO OFICIAL DE IDENTIFICACIÓN EXPEDIDO POR EL PAIS O TERRITORIO DE RESIDENCIA\n05 = CERTIFICADO DE RESIDENCIA\n06 = OTRO DOCUMENTO PROBATORIO\n',
  `REG_IDF_IDEF_IDOtro_ID` VARCHAR(20) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - IDEmisorFactura - IDOtro - ID\nNúmero de identificación en el país de residencia',
  `REG_IDF_NumSerieFacturaEmisor` VARCHAR(60) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - NumSerieFacturaEmisor\nNúmero+Serie que identifica a la factura emitida',
  `REG_IDF_NumSerieFacturaEmisorResumenFin` VARCHAR(60) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - NumSerieFacturaEmisorResumenFin\nNúmero+serie que identifica a la ultima factura cuando el Tipo de Factura es un asiento resumen de facturas.',
  `REG_IDF_FechaExpedicionFacturaEmisor` DATE NOT NULL COMMENT 'RegistroLRFacturasRecibidas - IDFactura - FechaExpedicionFacturaEmisor\nFecha de expedición de la factura. En la base de datos se guarda como un tipo date, en el envío se trasmite en la forma ''DD-MM-YYYY''',
  `REG_FR_TipoFactura` VARCHAR(2) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - TipoFactura\nEspecificación del tipo de factura a dar de alta: factura normal, factura rectificativa, tickets, factura emitida en sustitución de facturas. Posibles valores:\nF1 = Factura\nF2 = Factura Simplificada (ticket)\nF3 = Factura emitida en sustitución de facturas simplificadas facturadas y declaradas\nF4  = Asiento resumen de facturas\nF5 = Importaciones (DUA)\nF6  =Justificantes contables\nR1 = Factura Rectificativa (Error fundado en derecho y Art. 80 Uno Dos y Seis LIVA)\nR2 = Factura Rectificativa (Art. 80.3)\nR3 = Factura Rectificativa (Art. 80.4)\nR4 = Factura Rectificativa (Resto)\nR5 = Factura Rectificativa en facturas simplificadas',
  `REG_FR_TipoRectificativa` VARCHAR(1) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - TipoRectificativa\nCampo que identifica si el tipo de factura rectificativa es por sustitución o por diferencia. Posibles valores:\nS =  Por sustitución\nI  = Por diferencias\n',
  `REG_FR_FA_IDFA_NumSerieFacturaEmisor` VARCHAR(60) DEFAULT NULL COMMENT 'RegistroLRFacturasEmitidas - FacturaRecibida - FacturasAgrupadas - IDFacturaAgrupada - NumSerieFacturaEmisor\nNúmero+Serie que identifica a la factura emitida.',
  `REG_FR_FA_IDFA_FechaExpedicionFacturaEmisor` DATE DEFAULT NULL COMMENT 'RegistroLRFacturasEmitidas - FacturaRecibida - FacturasAgrupadas - IDFacturaAgrupada - FechaExpedicionFacturaEmisor\nFecha de expedición de la factura',
  `REG_FR_FR_IDR_NumSerieFacturaEmisor` VARCHAR(60) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - FacturasRectificadas - IDFacturaRectificada - NumSerieFacturaEmisor\nNúmero+Serie que identifica a la factura emitida de la que se va a hacer la rectificación.\n',
  `REG_FR_FR_IDR_FechaExpedicionFacturaEmisor` DATE DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - FacturasRectificadas - IDFacturaRectificada - FechaExpedicionFacturaEmisor\nFecha de expedición de la factura de la que se va a hacer la recitificación. Aunque se guarda como columna tipo DATE, en el momento del envio este campo se informa con el formato ''DD-MM-YYYY''.\n',
  `REG_FR_IR_BaseRectificada` DECIMAL(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ImporteRectificacion - BaseRectificada\nBase imponible de la factura sustituidas. Es decir, la base original de la factura que se quiere rectificar. Aunque el campo admite nulos si el tipo de la factura es rectificativa, entonces su información es obligatoria.\n',
  `REG_FR_IR_CuotaRectificada` DECIMAL(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ImporteRectificacion - CuotaRectificada\nCuota de la factura sustituidas. Es decir, la cuota original de la factura que se quiere rectificar. Aunque el campo admite nulos si el tipo de la factura es rectificativa, entonces su información es obligatoria.\n',
  `REG_FR_IR_CuotaRecargoRectificado` DECIMAL(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ImporteRectificacion - CuotaRecargoRectificado\nCuota de recargo de la factura sustituidas. Es decir, la cuota de recargo original de la factura que se quiere rectificar. Aunque el campo admite nulos si el tipo de la factura es rectificativa, entonces su información es obligatoria, en el caso de que haya cuota de recargo.\n',
  `REG_FR_FechaOperacion` DATE DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - FechaOperacion\nFecha en la que se ha realizado la operación siempre que sea diferente a la fecha de expedición. La columna es tipo DATE y se informa como ''DD-MM-YYYY''\n',
  `REG_FR_ClaveRegimenEspecialOTrascendencia` VARCHAR(2) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ClaveRegimenEspecialOTrascendencia\nClave que identificará el tipo de operación o el régimen especial con transcendencia tributaria. Posibles valores:\n01 = Operación de régimen común\n02 = Exportación\n03 = Operaciones a las que se aplique el régimen especial de bienes usados, objetos de arte, antigüedades y objetos de colección (135-139 de LIVA)\n04 = Régimen especial oro de inversión\n05 = Régimen especial agencias de viajes\n06 = Régimen especial grupo de entidades en IVA\n07 = Régimen especial grupo de entidades en IVA (Nivel Avanzado)\n08 = Régimen especial criterio de caja\n09 = Operaciones sujetas al IPSI / IGIC\n10 = Facturación de las prestaciones de servicios de agencias de viaje que actúan como mediadoras en nombre y por cuenta ajena (D.A.4ª RD1619/2012)\n11 = Cobros por cuenta de terceros de honorarios profesionales ....\n12 = Operaciones de seguros\n13 = Op. de arrendamiento sujetas a retención\nXX = Hay más tipos consulta documentación ...',
  `REG_FR_ClaveRegimenEspecialOTrascendenciaAdicional1` VARCHAR(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ClaveRegimenEspecialOTrascendencia\nClave que identificará el tipo de operación o el régimen especial con transcendencia tributaria. Posibles valores:\n01 = Operación de régimen común\n02 = Exportación\n03 = Operaciones a las que se aplique el régimen especial de bienes usados, objetos de arte, antigüedades y objetos de colección (135-139 de LIVA)\n04 = Régimen especial oro de inversión\n05 = Régimen especial agencias de viajes\n06 = Régimen especial grupo de entidades en IVA\n07 = Régimen especial grupo de entidades en IVA (Nivel Avanzado)\n08 = Régimen especial criterio de caja\n09 = Operaciones sujetas al IPSI / IGIC\n10 = Facturación de las prestaciones de servicios de agencias de viaje que actúan como mediadoras en nombre y por cuenta ajena (D.A.4ª RD1619/2012)\n11 = Cobros por cuenta de terceros de honorarios profesionales ....\n12 = Operaciones de seguros\n13 = Op. de arrendamiento sujetas a retención\nXX = Hay más tipos consulta documentación ...',
  `REG_FR_ClaveRegimenEspecialOTrascendenciaAdicional2` VARCHAR(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ClaveRegimenEspecialOTrascendencia\nClave que identificará el tipo de operación o el régimen especial con transcendencia tributaria. Posibles valores:\n01 = Operación de régimen común\n02 = Exportación\n03 = Operaciones a las que se aplique el régimen especial de bienes usados, objetos de arte, antigüedades y objetos de colección (135-139 de LIVA)\n04 = Régimen especial oro de inversión\n05 = Régimen especial agencias de viajes\n06 = Régimen especial grupo de entidades en IVA\n07 = Régimen especial grupo de entidades en IVA (Nivel Avanzado)\n08 = Régimen especial criterio de caja\n09 = Operaciones sujetas al IPSI / IGIC\n10 = Facturación de las prestaciones de servicios de agencias de viaje que actúan como mediadoras en nombre y por cuenta ajena (D.A.4ª RD1619/2012)\n11 = Cobros por cuenta de terceros de honorarios profesionales ....\n12 = Operaciones de seguros\n13 = Op. de arrendamiento sujetas a retención\nXX = Hay más tipos consulta documentación ...',
  `REG_FR_NumRegistroAcuerdoFacturacion` VARCHAR(15) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - NumRegistroAcuerdoFacturacion\nNúmero de registro obtenido al enviar la autorización en materia de facturación o de libros registro.',
  `REG_FR_ImporteTotal` DECIMAL(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - ImporteTotal\nDescripción del objeto de la factura. Aunque es un campo TEXT, en realidad el máximo de caracteres en la comunicación serán 500.',
  `REG_FR_BaseImponibleACoste` DECIMAL(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - BaseImponibleACoste\nSe utiliza sólo en los grupos de IVA.',
  `REG_FR_DescripcionOperacion` TEXT COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - DescripcionOperacion\nDescripcion del objeto de la factura',
  `REG_FR_DF_ISP_DI_DT1_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - InversionSujetoPasivo - DetallaIVA1 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT1_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA1 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT1_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA1 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT1_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA1 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT1_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -DesgloseFactura - InversionSujetoPasivo - DetalleIVA1 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_ISP_DI_DT2_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA2 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT2_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - InversionSujetoPasivo - DetalleIVA2 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT2_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA2 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT2_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA2 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT2_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA2 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_ISP_DI_DT3_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetallaIVA3 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT3_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA3 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT3_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA3 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT3_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA3 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT3_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DetalleIVA3 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_ISP_DI_DT4_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -DesgloseFactura - InversionSujetoPasivo - DetalleIVA4 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT4_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nFacturaRecibida - DesgloseFactura - InversionSujetoPasivo - DesgloseIVA - DetalleIVA4 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT4_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - InversionSujetoPasivo - DesgloseIVA - DetalleIVA4 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT4_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA4 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT4_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA4 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_ISP_DI_DT5_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetallaIVA5 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT5_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA5 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT5_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - InversionSujetoPasivo - DesgloseIVA - DetalleIVA5 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT5_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA5 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT5_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - InversionSujetoPasivo - DesgloseIVA - DetalleIVA5 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_ISP_DI_DT6_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetallaIVA6 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_ISP_DI_DT6_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA6 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT6_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA6 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_ISP_DI_DT6_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA6 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_ISP_DI_DT6_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  InversionSujetoPasivo - DesgloseIVA - DetalleIVA6 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  
  `REG_FR_DF_DGI_DI_DT1_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT1_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT1_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetalleIVA1 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT1_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT1_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT1_PorcentCompensacionREAGYP` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT1_ImporteCompensacionREAGYP` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 1 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',

  `REG_FR_DF_DGI_DI_DT2_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA2 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT2_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetalleIVA2 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT2_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA2 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT2_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetalleIVA2 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT2_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA2 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT2_PorcentCompensacionREAGYP` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT2_ImporteCompensacionREAGYP` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 2 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',

  `REG_FR_DF_DGI_DI_DT3_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetallaIVA3 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT3_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura -DesgloseIVA - DetalleIVA3 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT3_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA3 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT3_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA3 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT3_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA3 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT3_PorcentCompensacionREAGYP` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT3_ImporteCompensacionREAGYP` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 3 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',
  
  `REG_FR_DF_DGI_DI_DT4_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA4 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT4_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nFacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA4 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT4_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA4 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT4_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA4 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT4_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA4 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT4_PorcentCompensacionREAGYP` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT4_ImporteCompensacionREAGYP` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 4 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',
  
  `REG_FR_DF_DGI_DI_DT5_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetallaIVA5 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT5_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA5 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT5_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA5 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT5_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA5 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT5_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA5 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT5_PorcentCompensacionREAGYP` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT5_ImporteCompensacionREAGYP` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 5 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',

  `REG_FR_DF_DGI_DI_DT6_TipoImpositivo` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetallaIVA6 - TipoImpositivo.\nPorcentaje aplicado sobre la Base Imponible para calcular la cuota.',
  `REG_FR_DF_DGI_DI_DT6_BaseImponible` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA6 - BaseImponible.\nMagnitud dineraria sobre la cual se aplica un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT6_CuotaSoportada` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA6 - CuotaSoportada.\nCuota resultante de aplicar a la base imponible un determinado tipo impositivo',
  `REG_FR_DF_DGI_DI_DT6_TipoREquivalencia` DECIMAL(5,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA6 - TipoRecargoEquivalencia.\nPorcentaje asociado en función del tipo de IVA',
  `REG_FR_DF_DGI_DI_DT6_CuotaREquivalencia` DECIMAL(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura -DesgloseIVA - DetalleIVA6 - CuotaRecargoEquivalencia.\nCuota resultante de aplicar a la base imponible el tipo de recargo de equivalencia',
  `REG_FR_DF_DGI_DI_DT6_PorcentCompensacionREAGYP` decimal(5,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida -  DesgloseFactura - DesgloseIVA - DetallaIVA1 - PorcentCompensacionREAGYP.\nPorcentaje aplicado para la compensacion REAGYP.',
  `REG_FR_DF_DGI_DI_DT6_ImporteCompensacionREAGYP` decimal(14,2) DEFAULT NULL COMMENT 'IVA 6 DE 6 POSIBLES\nRegistroLRFacturasRecibidas - FacturaRecibida - DesgloseFactura - DesgloseIVA - DetalleIVA1 - ImporteCompensacionREAGYP.\nMagnitud dineraria sobre del importe de la compensacion REAGYP',
  
  `REG_FR_CNT_NombreRazon` varchar(40) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - NombreRazon\nNombre-razón social de la contraparte de la operación. Proveedor en facturas recibidas',
  `REG_FR_CNT_NIFRepresentante` varchar(9) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - NIFReepresentante\nNIF del representante de la contraparte de la operación. Proveedor en facturas recibidas',
  `REG_FR_CNT_NIF` varchar(9) NOT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - NIF\nIdentificador del NIF de la contraparte de la operación. Proveedor en facturas recibidas',
  `REG_FR_CNT_IDOtro_CodigoPais` varchar(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - IDOtro - CodigoPais\nIDOtro, solo es de obligado cumplimiento si hay que proporcionar información adicional de la contraparte. Si aun no siendo obligado se cumplimenta esta información aparece en la consulta directa de la web de AEAT.\nCódigo del país asociado contraparte de la operación (cliente) de facturas expedidas (ISO 3166-1 alpha-2 codes)',
  `REG_FR_CNT_IDOtro_IDType` varchar(2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - IDOtro - IDType\nClave para establecer el tipo de identificación en el pais de residencia. Posibles valores:\n02 = NIF-IVA\n03 = PASAPORTE\n04 = DOCUMENTO OFICIAL DE IDENTIFICACIÓN EXPEDIDO POR EL PAIS O TERRITORIO DE RESIDENCIA\n05 = CERTIFICADO DE RESIDENCIA\n06 = OTRO DOCUMENTO PROBATORIO\n',
  `REG_FR_CNT_IDOtro_ID` varchar(20) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - Contraparte - IDOtro - ID\nNúmero de identificación en el país de residencia',
  `REG_FR_FechaRegContable` date DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - FechaRegContable\nFecha del registro contable de la operación. Se utilizará para el plazo de remisión de las facturas recibidas\nSe guarda como DATE, se informa como ''DD-MM-YYYY''',
  `REG_FR_CuotaDeducible` decimal(14,2) DEFAULT NULL COMMENT 'RegistroLRFacturasRecibidas - FacturaRecibida - CuotaDeducible\nCuota deducible',
  PRIMARY KEY (`IDEnvioFacturasRecibidas`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8 COMMENT='En esta tabla se guardan los mensajes que debe de procesar la utilidad de envío de facturas emitidas al sistema SII. Debe grabar un registro por cada una de las facturas que quiera enviar o modificar tras su envío.';

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
